#!/bin/bash

set -eu
set -o pipefail

lfs() {
  if [[ ! -f .gitattributes ]]; then
    return 0
  fi

  if ! grep -q 'filter=lfs diff=lfs merge=lfs -text' .gitattributes; then
    return 0
  fi

  if ! type -p git-lfs >/dev/null; then
    return 0
  fi

  git lfs post-merge "$@"
}

main() {
  lfs "$@"
}

main "$@"
