#!/bin/bash

set -eu
set -o pipefail

readonly ESC=$(printf '\033')
readonly BLUE="${ESC}[34m"
readonly NO_COLOR="${ESC}[m"

readonly EXECUTABLES=(pre-commit)

blue() {
  echo -n "${BLUE}${1}${NO_COLOR}"
}

# Verify if executables are in the PATH.
check_executables() {
  for e in "${EXECUTABLES[@]}"; do
    if ! type -p "${e}" >/dev/null; then
      echo "${e} not found on the system" >&2
      return 1
    fi
  done
}

lfs() {
  if [[ ! -f .gitattributes ]]; then
    return 0
  fi

  if ! grep -q 'filter=lfs diff=lfs merge=lfs -text' .gitattributes; then
    return 0
  fi

  if ! type -p git-lfs >/dev/null; then
    return 0
  fi

  git lfs post-checkout "$@"
}

main() {
  check_executables

  local -r config_base=".pre-commit-config.yaml"

  local config="${XDG_CONFIG_HOME}/pre-commit/${config_base}"
  if [[ -f "${config_base}" ]]; then
    config="${config_base}"
  fi

  local -r cmd="pre-commit run --config ${config} --hook-stage post-checkout --color always"

  printf "Running %s...\n\n" "$(blue "'${cmd}'")" >&2
  eval "${cmd}"

  lfs "$@"
}

main "$@"
